### ISSUE TITLE
Verify email address

### ISSUE THREAD

**Issue by isaacjwilliams** [desotocaverns/hola#14]
Customers can put anything in the email field. Verify that it is a real email address.

**Comment by isaacjwilliams** [comment]
We now validate email addresses - well, somewhat. The email "jake" doesn't get through (yay), but the email "jake@notarealdomain.com" does (i haz sad).

**Comment by imathis** [comment]
For ticket delivery we should probably be sure it at least conforms to an email addresses pattern. Something@something.something, which works fine as…

```
^.+@.+?\..+$
```

**Comment by isaacjwilliams** [comment]
@imathis I already have that behavior working. Is that good enough?

**Comment by imathis** [comment]
It's good enough for me! Anything more probably ends up being busywork. If it ends up mattering in the real world, we can go back and add it.
