### ISSUE TITLE
PCI DSS

### ISSUE THREAD

**Issue by isaacjwilliams** [desotocaverns/hola#19]
We are using our own custom form to accept credit card data, and that data can be completely accessed by our JS. Should someone perform a man-in-the-middle attack and put bad script in our HTML document, they could send the card data accepted by our form straight to them. I was reading [Stripe's support answer about DSS 3.1](https://support.stripe.com/questions/what-about-pci-dss-3-1), and it seems like the only thing could easily relieve us of a compliance burden would be their Checkout iframe. This is greatly unfortunate.

Of course, if we just ignore those facts, compliance with DSS doesn't matter until someone attacks us. We should address this issue in our talk today. Dad is willing to explain things in further detail if I can't.

**Comment by imathis** [comment]
As a matter of record, we've decided to let Stripe handle this with their Checkout.js system and figure out how to adapt our app to work accordingly.

**Comment by isaacjwilliams** [comment]
I'll close this issue when Checkout integration is finished.
