### ISSUE TITLE
Add database tables for storing tickets and purchases

### ISSUE THREAD

**Issue by imathis** [desotocaverns/hola#2]

**Comment by imathis** [comment]
There's a [Table](https://docs.google.com/drawings/d/1sFzIIOsN7u-wixed0Vq86xVnfL3_k5cmDu8oo0ct1I8/edit?pli=1) which describes how this should be done.

**Comment by imathis** [comment]
It occurs to me that it may be good to add another table ForSale (or whatever). This would list ticket ids and allow us to order them for the sales page.

**Comment by imathis** [comment]
… that way if you want to remove a ticket from sale, but not delete it, you could update that table. I'm also fine with setting a property on the Packages table if that's a better move. Basically we need a way to have a set of tickets which are for sale and set the order of those tickets.

**Comment by isaacjwilliams** [comment]
Alright, the database tables are up and purchase records are stored in them upon purchase. The Packages table now has a for_sale row, as well.
