### ISSUE TITLE
Calculate prices

### ISSUE THREAD

**Issue by imathis** [desotocaverns/hola#20]
It would be splendid if we could split up the ticket selection form from the rest of the checkout flow, such that we could submit the form over ajax and retrieve the subtotal, tax, and total price information as a response. I am happy to handle the ajax form portion of this.

I'm not sure how this affects the Checkout.js portion of things. From their docs it looks like we need to provide a final price in the form of an data-attribute on the script tag for embedding the Stripe javascript. If that's the case, I assume we'll want to dynamically write that script tag when the time comes. I'm happy to help out with that too.

**Comment by isaacjwilliams** [comment]
Prices are now calculated in the JS for displaying to the user and on the server-side for verification. Records are not saved if the two do not match. See [commit 50](https://github.com/desotocaverns/hola/commit/2252db1a13e9857f734fad2ad045fa5f6b1d8a16).
