### ISSUE TITLE
Integrate iframe checkout from Stripe

### ISSUE THREAD

**Issue by imathis** [desotocaverns/hola#22]
After #21, the "continue to checkout" button will trigger the next step, which is to collect payment information with the stripe popup and then submit that information to stripe to complete the transaction. Here we'll need to insert the price calculated from #20 and if the form accepts custom information, perhaps the purchase ID generated from #21.

I'm not sure what it will take to link a purchase with a stripe transaction on our end, or what that should look like. If you run into any tricky parts in that process which might affect the user experience, let me know and we can discuss them.

**Comment by isaacjwilliams** [comment]
The iframe checkout from Stripe is fully integrated!

In answer to your question, we save the [charge ID](https://stripe.com/docs/api/ruby#retrieve_charge) received from Stripe with the record so we can look up the transaction in Stripe whenever we want.
