### ISSUE TITLE
Ensure that purchase records are preserved

### ISSUE THREAD

**Issue by imathis** [desotocaverns/hola#23]
We want to be sure that whatever a user purchases never changes in the database. If a package is edited, it should not change the record of what someone purchased. This is most important in terms of handling pricing. I'd hate for someone to be charged more than they expect, or to receive an email which makes it look like this has occurred, simply because someone was updating a ticket or package on the site during their checkout process.

**Regarding Reporting**

When I think about reporting this does become a bit difficult. If I want to find out how many Fun Pacs we've sold, (that's a package of one tour and two attractions) It would be unfortunate if changing a spelling error or a price gave me incomplete information. Obviously from the computer's perspective, we've sold two different packages, but from the real-world perspective they are the same. Obviously we haven't build reporting yet, but I anticipate that this change will affect how we build it.

Perhaps we could generate a "fingerprint" for each package based on what it contains. So if a package contains one cave tour and two attractions it would have a matching fingerprint, such that whatever the price or name of that package is can always be queried by that fingerprint.

This may sound a bit YAGNI (You Aren't Going to Need It) and it may be something we can handle with a migration when that day arises.

**Comment by isaacjwilliams** [comment]
<pre>                         ┌─────────────────┐
                         │      Sales      │
                         └─────────────────┘
         ┌────────────────────────────────────────────────┐
         │         ┌─────────────────────────────┐        │
         │         │Sale                         │        │
         │         │                             │        │
         │         │  name                       │        │
         │         │  email                      │        │
         │         │  tax                        │        │
         │         │  total_price                │        │
         │         │  charge_id                  │        │
         │         │                             │        │
         │         │  has_many :purchases        │        │
         │         └─────────────────────────────┘        │
         │                                                │
         │                              ┌ - - - - - - -   │
         │         ┌─────────────────────Quantity is   |  │
         │         │Purchase (Abstract) |expressed as     │
         │         │                     multiple rows.|  │
         │         │  id, type (STI)    └ - - - -│- - -   │
         │         │  sale_id                    │        │
         │         │  redeemed_on                │        │
         │         │  redemption_code            │        │
         │         │  expires_on                 │        │
         │         │                             │        │
         │         └─────────────────────────────┘        │
         │                        ▲                       │
         │            ┌───────────┴───────────┐           │
         │            │                       │           │
         │            │                       │           │
         │┌──────────────────────┐ ┌─────────────────────┐│
         ││PackagePurchase       │ │TicketPurchase       ││
         ││                      │ │                     ││
         ││  package_id          │ │  ticket_id          ││
         ││  package_revision_id │ │  ticket_revision_id ││
         │└──────────────────────┘ └─────────────────────┘│
         └────────────────────────────────────────────────┘
                        ┌─────────────────┐
                        │ Administration  │
                        └─────────────────┘
┌──────────────────────────────────────────────────────────────────┐
│                       ┌─────────────────┐                        │
│                       │     Tickets     │                        │
│                       └─────────────────┘                        │
│           ┌───────────────┐          ┌───────────────┐           │
│           │Ticket         │          │TicketRevision │           │
│           │               │          │               │           │
│           │  name         │          │  revision     │           │
│           │  price        │          │  ticket_id    │           │
│           │               │          │  ticket_price │           │
│           └───────────────┘          └───────────────┘           │
├──────────────────────────────────────────────────────────────────┤
│                       ┌─────────────────┐                        │
│                       │    Packages     │                        │
│                       └─────────────────┘                        │
│                                                                  │
│┌──────────────────────────────┐  ┌──────────────────────────────┐│
││Package                       │  │PackageRevision               ││
││                              │  │                              ││
││  name                        │  │  revision                    ││
││  price                       │  │  package_id                  ││
││                              │  │  package_price               ││
││  has_many :package_tickets   │  │  package_tickets             ││
│└──────────────────────────────┘  └──────────────────────────────┘│
│                                                                  │
│                  ┌──────────────────────────────┐                │
│                  │PackageTicket                 │                │
│                  │                              │                │
│                  │  validates_uniqueness_of     │                │
│                  │    ticket_revision, scope    │                │
│                  │      [package_id, ticket_id] │                │
│                  │                              │                │
│                  │  package_id                  │                │
│                  │  package_revision_id         │                │
│                  │  ticket_id                   │                │
│                  │  ticket_revision_id          │                │
│                  └──────────────────────────────┘                │
└──────────────────────────────────────────────────────────────────┘</pre>

What do you think of this model? I believe it will do everything you require of it. :smile:

**Comment by isaacjwilliams** [comment]
Here's a sales story: Jim buys a Fun Pac (a cave tour and five attraction tickets). In the database, a Sale is created that references his Purchases (in this case, one PackagePurchase). His PackagePurchase references the Fun Pac with a package_id and the Fun Pac that was the Fun Pac at the time of his purchase with the package_revision_id. Whenever Jim looks at the success page or at the email he received, he will be looking at data pulled from the PackageRevision object (a snapshot of what the Fun Pac was when he bought it).

**Comment by isaacjwilliams** [comment]
Here's an administration story: Jake (an admin) looks at the Fun Pac in the list of Packages. Jake decides that the Fun Pac is too cheap (that much fun for only $28.99?!), and changes the price to $34.99. In the Package table, the Fun Pac's price is changed, and in the PackageRevision table, a new PackageRevision (a snapshot of the new Fun Pac) is created for posterity. Even though Jake changed the Fun Pac, no one's orders will be messed up and no emails will be sent with wrong information because they all reference the older PackageRevision.

**Comment by isaacjwilliams** [comment]
More stories, yay! Julie decides to make a new Package, the Ultra-Fun Pac, that contains 2 cave tours and 10 attractions. She goes through the form process, and the database adds a new Package to the Package table and a new PackageRevision to the PackageRevision table. The Package object contains 12 PackageTickets (2 that reference the cave tour ticket and 10 that reference the attraction ticket). If Julie decides to change the Ultra-Fun Pac, the Package _will_ change but the PackageRevision will not (so that no one's orders are messed up); instead, a new PackageRevision will be created for all new PackagePurchases and TicketPurchases to reference.

**Comment by imathis** [comment]
Wow, nice work! I like the revision tracking system and It seems like you've covered concerns I had. Also, that text graphic is awesome. How did you make it?

**Comment by isaacjwilliams** [comment]
Thanks! I used [Monodraw](http://monodraw.helftone.com) for the graphic.
