### ISSUE TITLE
Keep forms available to user for easy editing.

### ISSUE THREAD

**Issue by imathis** [desotocaverns/hola#28]
I'd like the checkout process to work like an accordion, where you can see the tickets, then you hit next (the submit button) and the tickets are hidden and the next form expands underneath. This way a user can go back and modify something by expanding that section again.

**Comment by isaacjwilliams** [comment]
As of [commit #51](https://github.com/desotocaverns/hola/commit/eaed1e93f3c19334a6b358cad7f1d30631282154), this is completely implemented. All forms are shown on one page to the user and are kept in an accordion. Any changes they perform on their purchase are automatically reflected in the database.
