### ISSUE TITLE
Allow a user to purchase multiple different packages

### ISSUE THREAD

**Issue by isaacjwilliams** [desotocaverns/hola#3]

**Comment by imathis** [comment]
How are you thinking of doing this? I was thinking each item could be a list item in an unordered list with a [number input](http://www.html5tutorial.info/html5-number.php). I'll probably come back behind it and add javascript buttons to increment and decrement the value, since many browsers don't offer those buttons by default.

**Comment by isaacjwilliams** [comment]
I was thinking of having an add button where users could add different kinds of tickets. That way, we wouldn't have to display all the tickets and they wouldn't have to have a 0 in tons of fields.

**Comment by imathis** [comment]
I think people are going to want to view each ticket (there will only be like 10 or so) and compare them to choose the ticket or tickets that are right for them. I think a one-page experience will be better for something like this.

Here's a story: 
1. A user is browsing the cave website, sees the link to buy tickets, clicks that, comes to a page with a menu showing each ticket, the price and a description. (kind of like a dinner menu). They can quickly see how much it will cost to visit the cave.
2. They tap a button to add tickets to their cart and they can see the total increasing automatically. (I'll be happy to write the JS for this part).
3. Then they click buy and the menu slides away and the rest of the form comes into view (again I can handle the JS so no worries). 
4. They finish filling out the form and hit submit. They get their confirmation and then they can go back to the site or whatever.

For the user, everything happens on one page (except the "Success! here's your ticket" page), but javascript hides and shows the parts they need to see.

**Comment by isaacjwilliams** [comment]
I like it! I'll do it that way, then. I hope to have this issue closed by the end of today.

**Comment by imathis** [comment]
:metal:
