### ISSUE TITLE
Update purchasing flow

### ISSUE THREAD

**Issue by isaacjwilliams** [desotocaverns/hola#40]
- [x] 1. The user sees a list of tickets and packages. Next to each ticket, there is an "Add to cart" button and a quantity dropdown with a default of one.
- [x] 2. The user clicks "Continue to summary" (or whatever) and is shown a personal information form with a static cart under it.
- [x] 3. The user can, at any time, edit their cart. When they save their changes, they are taken to step two. If they have already filled out the personal information form, it is shown as a static card (that can, of course, be edited).
- [x] 4. From step two the user clicks "Purchase" and is shown the Stripe card form.
- [x] 5. Once the Stripe form is submitted, the user is taken to the success page where they can view their tickets.

**Comment by imathis** [comment]
Exactly. You've distilled this quite well from our conversation. :+1:

**Comment by imathis** [comment]
Oh, I will add that the "Add to cart" action from item 1, should add the item with ajax submission of the "menu form". Then the cart info panel should be updated to reflect the new number of items and the total.

**Comment by imathis** [comment]
I've made some design changes which you can see in the latest commit to #39 that reveal a difficulty you'll have when implementing the new add to cart buttons. Here's a screen shot.

<img width="497" alt="add-to-cart" src="https://cloud.githubusercontent.com/assets/12732/9780498/39d5fbf8-574f-11e5-9844-9e8616710aa2.png">

Note that each select box defaults to [1]. When you hit add to cart, it will submit that form causing 1 of each ticket type to be added. I'm thinking we'll need to handle these items in separate forms or something like that. This is just a heads up in case you haven't thought this far ahead yet.

**Comment by isaacjwilliams** [comment]
@imathis: I've already thought through the form flow and arrived at the same conclusion as you; each ticket has its own "add to cart" mini-form. Thanks for the heads up anyway! :+1:
