### ISSUE TITLE
If a cart item's quantity is changed to zero it should be removed

### ISSUE THREAD

**Issue by imathis** [desotocaverns/hola#42]

**Comment by imathis** [comment]
I don't believe this is fixed yet. Here's a screen shot from the latest.
<img width="226" alt="cart-items-0" src="https://cloud.githubusercontent.com/assets/12732/9829578/864459f4-58cf-11e5-9948-9f861359459c.png">

**Comment by isaacjwilliams** [comment]
I do believe it's really working now. :)
