### ISSUE TITLE
Make it possible to sort the order of tickets and packages

### ISSUE THREAD

**Issue by imathis** [desotocaverns/hola#53]

**Comment by imathis** [comment]
I see a few options for how this might work.
1. Up down arrows on tickets and packages, clicking them shifts the order by one and ajax refreshes the pane to make that work.
2. A box where you can type the order value. So you could add a 1 to put something at the top, a or 2 for second place. Any number equal to or greater than the number of tickets (or packages) would put it on the bottom.
3. Drag and drop. This is how it would work with most apps, but it adds some complexity and a lot of javascript. It's nice, but to me it's expensive, and I'd rather spend that on areas which provide direct value to the customer.

I think order is something you'd set on the index of tickets, not really on a ticket edit page, even though it's a property of a ticket. If you have questions, I'm happy to discuss this whenever.

**Comment by isaacjwilliams** [comment]
Found a bug!

**Comment by isaacjwilliams** [comment]
Gone for real now. :smile:
