### ISSUE TITLE
Simplify (for the user) setting ticket's "for sale" status

### ISSUE THREAD

**Issue by imathis** [desotocaverns/hola#65]
Right now a ticket's "for sale" status is a date field. This works great for tickets that you want to set to go on sale in the future, but for other scenarios it's confusing. Also, how do you remove a ticket from sale? What I'd really like to be able to do is set a ticket for sale, "No", "Yes", "On a date". Then an additional set of fields can set the date. Here's a mockup.

<img width="761" alt="screen shot 2015-09-21 at 11 13 35 pm" src="https://cloud.githubusercontent.com/assets/12732/10010937/570308de-60b8-11e5-9f40-7ae69c987ee5.png">

What say you?

**Comment by imathis** [comment]
And of course as soon as I post this I see the ambiguity of "after", I'd change that to say "on a date".

**Comment by isaacjwilliams** [comment]
Lookin' good! I'll work on that pronto.
