### ISSUE TITLE
Group ticket purchases (when they are added individually)

### ISSUE THREAD

**Issue by imathis** [desotocaverns/hola#69]
Scenario: If I add an Explorer Fun Pac to my cart then I add another, they are not grouped together in the Cart Summary page. Here's a screen shot.

<img width="627" alt="screen shot 2016-01-29 at 6 28 13 pm" src="https://cloud.githubusercontent.com/assets/12732/12691948/8b2e37e6-c6b6-11e5-9b6a-31ec4c85a9b7.png">

They are also displayed separately when I edit my cart and in the final ticket.

**Comment by imathis** [comment]
This seems to happen on my dev machine but a reseed made it go away. I'm not sure what that was about. Sorry for the noise.

**Comment by imathis** [comment]
This happened in production. I think it occurs when a package is changed. From then on when I purchase that package. Each time it is added to the cart it is added as a separate item. As far as I can tell this only seems to affect packages. Right now every package on the ticket store (in production) is facing this issue, though I don't believe I have edited them all. I'm not sure what the cause is yet.

**Comment by isaacjwilliams** [comment]
This bug occurs when a package is edited. It affects tickets as well as packages.
