### ISSUE TITLE
Repopulate the form with user inputs when verification fails

### ISSUE THREAD

**Issue by isaacjwilliams** [desotocaverns/hola#7]

**Comment by isaacjwilliams** [comment]
The pieces of the form that reach the server (name, quantities, packages) now repopulate on error; however, the credit card field does not repopulate because it never gets past the JS. I'm not going to work on any more validation because I need to know how we want to handle form input.

I also thought of using masked card data. By the time the form data gets past the JS, we can be sure that the card was correct because we will already have received the Stripe token (which is retrieved by the JS before the form is submitted). If the model validation fails, we can just repopulate with masked card data (E.G. 1234********1314) - we don't need the card data anymore because we already have the Stripe token.

**Comment by imathis** [comment]
Yeah if we already have a valid stripe token, I'd love to avoid asking the to re-enter card information. That's one thing that commonly annoys me with shopping cart experiences, one failure requires everything to be entered in again all too frequently.
