### ISSUE TITLE
Send email to a list of addresses when tickets are purchased

### ISSUE THREAD

**Issue by imathis** [desotocaverns/hola#72]
It would be great if in the Store Settings page, you could add a comma (or newline) separated list of email addresses to receive mail whenever tickets are purchased. I think the email that is sent would be a plain text version of the email receipt without the barcode.

**Comment by isaacjwilliams** [comment]
@imathis So, if isaac@thewilliams.ws is on the comma-seperated list, I get an email _every time_ someone buys something?

**Comment by isaacjwilliams** [comment]
Almost done, see 4c16f45116ed9fcf95cdf69fe55c93ed4601d13b. As of now, the receipt copies sent to the admins are rich and have the QR codes in them.
