### ISSUE TITLE
Missing template?

### ISSUE THREAD

**Issue by imathis** [desotocaverns/hola#76]
When I complete a sale (locally) on the master branch with my database migrated and with the server restarted, I get this error.

```
Missing template sales/charge, application/charge with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :jbuilder]}. Searched in: …
```

**Comment by isaacjwilliams** [comment]
@imathis I'm not getting this error. I believe it's something on your machine!

**Comment by isaacjwilliams** [comment]
I'm seeing this in production. Looking into it now...

**Comment by isaacjwilliams** [comment]
The problem is with the secret Stripe API ENV variable key. I fixed the one on Heroku, and you probably need to fix the one on your machine. The variable name has been changed from STRIPE_API_KEY to the more specific STRIPE_SECRET_KEY.
