### ISSUE TITLE
Authenticate administrators for package editing

### ISSUE THREAD

**Issue by isaacjwilliams** [desotocaverns/hola#8]
We could just use basic http authentication, but then whenever an employee who knows the password is fired, you'd have to reset the password (which sucks). We could also have an entire admin model with sign in and the like (maybe?). How do we want to do this?

**Comment by imathis** [comment]
Crazy how scope just creeps up on us eh? I think we probably need to use authenticate with email address and passwords. So now we have the issue of how to handle authorizing sign ups. I'm guessing it should be an invitation system and there will be users who are admins who can initiate invitations and remove users. I suspect this would be something like this…
1. There is a users page, where an admin can add a user, providing an email address, and checking whether the user should have admin rights or not.
2. An email is sent with a tokened link which allows them to create a password.
3. Now the users page shows their account. From where an admin can delete the user or possibly reset their password.
4. We will need a "forgot password" email option on the sign in form.

Also there's a bit of a chicken and egg problem. How do you get an admin user signed up? :)

This is a lot of work, but some of it may be possible to build with pre-existing tools. Your dad may know of some to recommend.

**Comment by isaacjwilliams** [comment]
My latest commit, "Basic admin authentication", restricts access to package editing and purchase showing while allowing admins to sign in and view said areas. However, it allows anyone to sign up. I'm going to work on only allowing an existing admin to add new admins next.

In regards to the chicken and egg "first admin" problem, I will most likely have to manually set up the first admin - maybe @imathis? :blush:
